teamspace/urls.py
"""
URL Configuration

For more information on URLs, see:
https://docs.djangoproject.com/en/1.10/topics/http/urls/
"""
from django.conf.urls import include
from django.conf.urls import url
from teamspace.views import dashboard
from teamspace.views import frontend
from teamspace.views import google
from teamspace.views import organization
from teamspace.views import team

handler403 = 'teamspace.views.error'
handler404 = 'teamspace.views.error'

urlpatterns = [
    # Frontend routes
    url(
        r'^',
        include(
            [
                url(r'^$', frontend.home, name='home'),
                url(r'^about/$', frontend.about, name='about'),
                url(r'^login/$', frontend.login, name='login'),
                url(r'^logout/$', frontend.logout, name='logout'),
                url(r'^signup/$', frontend.signup, name='signup'),
            ],
            namespace='frontend',
        ),
    ),

    # Dashboard routes
    url(
        r'^d/',
        include(
            [
                # Root dashboard routes
                url(r'^$', dashboard.home, name='home'),

                # Account management routes
                url(
                    r'^u/',
                    include(
                        [
                            url(
                                r'^edit/$',
                                dashboard.user_edit,
                                name='edit',
                            ),
                            url(
                                r'^password/$',
                                dashboard.user_password,
                                name='password',
                            ),
                        ],
                        namespace='user',
                    ),
                ),

                # Organization access/creation routes
                url(
                    r'^o/',
                    include(
                        [
                            url(
                                r'^create/$',
                                dashboard.orgs_create,
                                name='create',
                            ),
                            url(
                                r'^view/$',
                                dashboard.orgs_view,
                                name='view',
                            ),
                        ],
                        namespace='organization',
                    ),
                ),
            ],
            namespace='dashboard',
        ),
    ),

    # Organization routes
    url(
        r'^o/([0-9]+)/',
        include(
            [
                # Root organization routes
                url(r'^$', organization.home, name='home'),
                url(r'^delete/$', organization.delete, name='delete'),
                url(r'^leave/$', organization.leave, name='leave'),
                url(r'^users/$', organization.users, name='users'),

                # Organization management routes
                url(
                    r'^m/',
                    include(
                        [
                            url(
                                r'^edit/$',
                                organization.manage_edit,
                                name='edit',
                            ),
                            url(
                                r'^users/$',
                                organization.manage_users,
                                name='users',
                            ),
                        ],
                        namespace='manage',
                    ),
                ),

                # Team access/creation routes
                url(
                    r'^t/',
                    include(
                        [
                            url(
                                r'^create/$',
                                organization.teams_create,
                                name='create',
                            ),
                            url(
                                r'^view/$',
                                organization.teams_view,
                                name='view',
                            ),
                        ],
                        namespace='team',
                    ),
                ),
            ],
            namespace='organization',
        ),
    ),

    # Team routes
    url(
        r'^t/([0-9]+)/',
        include(
            [
                # Root team routes
                url(r'^$', team.home, name='home'),
                url(r'^chat/$', team.chat, name='chat'),
                url(r'^delete/$', team.delete, name='delete'),
                url(r'^events/$', team.events, name='events'),
                url(r'^files/$', team.files, name='files'),
                url(r'^leave/$', team.leave, name='leave'),
                url(r'^users/$', team.users, name='users'),

                # Team management routes
                url(
                    r'^m/',
                    include(
                        [
                            url(r'^edit/$', team.manage_edit, name='edit'),
                            url(r'^users/$', team.manage_users, name='users'),
                        ],
                        namespace='manage',
                    ),
                ),
            ],
            namespace='team',
        ),
    ),

    # Provider routes
    url(
        r'^providers/',
        include(
            [url(r'^google/$', google.index, name='google')],
            namespace='providers',
        ),
    ),
]

teamspace/forms/event.py
"""
Event Forms

For more information on Forms, see:
https://docs.djangoproject.com/en/1.10/topics/forms/

For more information on ModelForms, see:
https://docs.djangoproject.com/en/1.10/topics/forms/modelforms/
"""
from django import forms
from teamspace.models import Event


class EventCreateForm(forms.ModelForm):

    class Meta:
        model = Event
        fields = ['title', 'description', 'start', 'end']
        error_messages = {
            'title': {
                'required': 'Please enter a title.',
            },
            'description': {
                'required': 'Please enter a short description.',
            },
        }

    def __init__(self, *args, **kwargs):
        self.owner = kwargs.pop('owner')
        self.parent = kwargs.pop('parent')
        super().__init__(*args, **kwargs)

    def save(self, commit=True):
        event = super().save(commit=False)
        event.owner = self.owner
        event.parent = self.parent
        if commit:
            event.save()
        return event

teamspace/forms/team.py
"""
Team Forms

For more information on Forms, see:
https://docs.djangoproject.com/en/1.10/topics/forms/

For more information on ModelForms, see:
https://docs.djangoproject.com/en/1.10/topics/forms/modelforms/
"""
from django import forms
from teamspace.models import Team
from teamspace.models import TeamMembership


class BaseTeamForm(forms.ModelForm):

    class Meta:
        model = Team
        fields = ['name', 'description']
        error_messages = {
            'name': {
                'required': 'Please enter your team name.',
                'unique': 'This team name is taken.',
            },
            'description': {
                'required': 'Please enter a team description.',
            },
        }


class TeamCreateForm(BaseTeamForm):

    def __init__(self, *args, **kwargs):
        self.owner = kwargs.pop('owner')
        self.parent = kwargs.pop('parent')
        super().__init__(*args, **kwargs)

    def save(self, commit=True):
        team = super().save(commit=False)
        team.owner = self.owner
        team.parent = self.parent
        if commit:
            team.save()
            TeamMembership.objects.create(team=team, user=team.owner)
        return team


class TeamEditForm(BaseTeamForm):
    pass

teamspace/views/team.py
"""
Team Controller

For more information on controllers (views), see:
https://docs.djangoproject.com/en/1.10/#the-view-layer

For the full list of requests and their responses, see:
https://docs.djangoproject.com/en/1.10/ref/request-response/
"""
import os
from django.conf import settings
from django.contrib import messages
from django.http import Http404
from django.shortcuts import redirect
from django.shortcuts import render
from django.views.static import serve
from teamspace.decorators import require_logged_in
from teamspace.decorators import require_team_member
from teamspace.decorators import require_team_owner
from teamspace.forms import AddMember
from teamspace.forms import EventCreateForm
from teamspace.forms import MessageCreateForm
from teamspace.forms import TeamEditForm
from teamspace.models import Event
from teamspace.models import File
from teamspace.models import Message
from teamspace.models import Team
from teamspace.models import TeamMembership
from teamspace.utils import format_errors
from teamspace.views import google


@require_logged_in
@require_team_member
def leave(request, id):
    """
    Deletes the membership record if the user is a member.
    """
    try:
        team = Team.objects.get(pk=id)
    except Team.DoesNotExist:
        raise Http404

    try:
        membership = TeamMembership.objects.get(user=request.user, team=team)
    except TeamMembership.DoesNotExist:
        raise Http404

    if membership:
        # Delete the membership
        membership.delete()
        team.members -= 1
        team.save()
        messages.info(request, 'You have left the team.')

    # Redirect the user back to the team view
    return redirect('organization:team:view', team.parent_id)


@require_logged_in
@require_team_owner
def delete(request, id):
    """
    Deletes the team if the user is the owner.
    """
    try:
        team = Team.objects.get(pk=id)
    except Team.DoesNotExist:
        raise Http404

    if team.owner == request.user:
        # Make sure the user is the owner
        team.delete()
        messages.info(request, 'The team has been deleted.')

    # Redirect the user back to the team view
    return redirect('organization:team:view', team.parent_id)


@require_logged_in
@require_team_member
def home(request, id):
    """
    Returns a view with the team and a parsed markdown description.
    """
    try:
        team = Team.objects.get(pk=id)
    except Team.DoesNotExist:
        raise Http404

    # Render the template with the data set
    return render(
        request,
        'backend/team/home.html',
        {'team': team, 'organization': team.parent},
    )


@require_logged_in
@require_team_member
def events(request, id):
    """
    Returns a view with the team and a list of events.
    """
    try:
        team = Team.objects.defer(*Team.DEFER).get(pk=id)
    except Team.DoesNotExist:
        raise Http404
    form = None

    if request.method == 'POST':
        # Process the post data in the form
        form = EventCreateForm(request.POST, owner=request.user, parent=team)

        if form.is_valid():
            # Check if the form is valid
            form.save()
            form = None
        else:
            messages.error(request, format_errors(form.errors))

    # Fetch the event list
    events = (
        Event.objects
            .select_related('owner')
            .filter(parent=team)
            .order_by('-start')
    )

    if not events:
        messages.info(request, 'There are no events to display.')

    # Render the template with the data set
    return render(
        request,
        'backend/team/events.html',
        {
            'team': team,
            'organization': team.parent,
            'form': form,
            'events': events,
        },
    )


@require_logged_in
@require_team_member
def files(request, id):
    """
    Returns a view with a file manager window of the team.
    """
    try:
        team = Team.objects.defer(*Team.DEFER).get(pk=id)
    except Team.DoesNotExist:
        raise Http404

    if request.method == 'GET' and 'file_id' in request.GET:
        try:
            # This does not scale well
            file_id = int(request.GET['file_id'])
            file = File.objects.get(pk=file_id)
            if file.parent == team:
                return serve(
                    request,
                    os.path.basename(file.location),
                    os.path.dirname(file.location),
                )
            else:
                messages.error(request, 'This file could not be found.')
        except ValueError:
            messages.error(request, 'Invalid file.')

    if request.method == 'POST':
        # Upload the requested file
        return redirect(
            google.authorize(
                request,
                {'team_id': team.id, 'file_id': request.POST['file_id']},
            )
        )

    # Fetch the file list
    files = (
        File.objects
            .select_related('owner')
            .filter(parent=team)
            .order_by('-created')
    )

    if not files:
        messages.info(request, 'There are no files to display. Share some!')

    # Render the template with the data set
    return render(
        request,
        'backend/team/files.html',
        {
            'team': team,
            'files': files,
            'organization': team.parent,
            'google': settings.PROVIDERS['GOOGLE'],
        },
    )


@require_logged_in
@require_team_member
def chat(request, id):
    """
    Returns a view with a chat window for the team.
    """
    try:
        team = Team.objects.defer(*Team.DEFER).get(pk=id)
    except Team.DoesNotExist:
        raise Http404
    form = None

    if request.method == 'POST':
        # Process the post data in the form
        form = MessageCreateForm(request.POST, owner=request.user, parent=team)

        if form.is_valid():
            # Check if the form is valid
            form.save()
            form = None
        else:
            messages.error(request, 'Your message could not be posted.')

    # Fetch the message list
    team_messages = (
        Message.objects
            .select_related('owner')
            .filter(parent=team)
            .order_by('-created')
    )

    if not team_messages:
        messages.info(request, 'There are no messages to display.')

    # Render the template with the data set
    return render(
        request,
        'backend/team/chat.html',
        {
            'team': team,
            'organization': team.parent,
            'form': form,
            'team_messages': team_messages,
        },
    )


@require_logged_in
@require_team_member
def users(request, id):
    """
    Returns a view with a list of members in the team.
    """
    try:
        team = Team.objects.defer(*Team.DEFER).get(pk=id)
    except Team.DoesNotExist:
        raise Http404

    # Fetch a list of team members
    users = TeamMembership.objects.select_related('user').filter(team=team)

    # Render the template with the data set
    return render(
        request,
        'backend/team/users.html',
        {'team': team, 'users': users, 'organization': team.parent},
    )


@require_logged_in
@require_team_owner
def manage_edit(request, id):
    """
    Returns a view where an owner can edit their team.
    """
    try:
        team = Team.objects.defer(*Team.DEFER).get(pk=id)
    except Team.DoesNotExist:
        raise Http404

    if request.method == 'POST':
        # Update the form with the post data
        form = TeamEditForm(request.POST, instance=team)

        if form.is_valid():
            # Check if the form is valid
            form.save()
            messages.success(request, 'Settings successfully saved.')
        else:
            messages.error(request, format_errors(form.errors))
    else:
        # Initialize the default form
        form = TeamEditForm(instance=team)

    # Render the template with the data set
    return render(
        request,
        'backend/team/manage_edit.html',
        {'form': form, 'team': team, 'organization': team.parent},
    )


@require_logged_in
@require_team_owner
def manage_users(request, id):
    """
    Returns a view with a list of users and a form to add users.
    """
    try:
        team = Team.objects.defer(*Team.DEFER).get(pk=id)
    except Team.DoesNotExist:
        raise Http404
    form = None

    if request.method == 'POST':
        if 'email' in request.POST:
            # Handle invitations by creating a membership record
            form = AddMember(request.POST, group=team)

            if form.is_valid():
                # Check if the form is valid
                form.add_member()
                team.members += 1
                team.save()
                messages.success(request, 'User successfully added.')
            else:
                messages.error(request, format_errors(form.errors))

        if 'id' in request.POST:
            # Handle removals by deleting the membership record
            # `id` is not user controlled, so assume it's safe
            remove_user_id = int(request.POST['id'])

            try:
                # Find and delete the membership record
                (
                    TeamMembership.objects
                        .get(user_id=remove_user_id, team=team)
                        .delete()
                )
            except TeamMembership.DoesNotExist:
                raise Http404
            team.members -= 1
            team.save()

    # Get a list of team members
    users = TeamMembership.objects.select_related('user').filter(team=team)

    if team.members == 1:
        # Check if the member count only includes the owner
        messages.info(
            request,
            'Your team does not have any members. Invite some!',
        )

    # Render the template with the data set
    return render(
        request,
        'backend/team/manage_users.html',

templates/backend/team/chat.html
{% extends 'backend/layouts/base.html' %}

{% block title %}
{{ team.name }}: Chat
{% endblock %}

{% block body %}
<!-- Page title -->
<div class="ui secondary pointing fluid menu">
    <h2 class="ui header">
        {{ team.name }}
        <div class="sub header">
            Chat
        </div>
    </h2>
</div>

<!-- Notifications -->
{% include 'backend/partials/notifications.html' %}

<!-- Body -->
<div class="row">
    <!-- Message form -->
    <form class="ui form" method="POST" action="{% url 'team:chat' team.id %}">
        <h4 class="ui dividing header">
            Post a Message
        </h4>
        <table class="simple form">
            <tr>
                <td>
                    <div class="field">
                        <input type="text" name="message" placeholder="Say something..." maxlength="255" required>
                    </div>
                </td>
                <td>
                    {% csrf_token %}
                    <button class="ui green button" type="submit">
                        Send
                    </button>
                </td>
            </tr>
        </table>
    </form>
    {% if team_messages %}
    <!-- Chat log -->
    <h4 class="ui dividing header expand">
        Chat Log
    </h4>
    {% for team_message in team_messages %}
    <div class="ui small message expand">
        <div class="message header">
            {{ team_message.owner.get_full_name }}, {{ team_message.created|timesince }} ago
        </div>
        <p>{{ team_message.message }}</p>
    </div>
    {% endfor %}
    {% endif %}
</div>
{% endblock %}

templates/backend/team/events.html
{% extends 'backend/layouts/base.html' %}

{% block title %}
{{ team.name }}: Events
{% endblock %}

{% block body %}
<!-- Page title -->
<div class="ui secondary pointing fluid menu">
    <h2 class="ui header">
        {{ team.name }}
        <div class="sub header">
            Events
        </div>
    </h2>
</div>

<!-- Notifications -->
{% include 'backend/partials/notifications.html' %}

<!-- Body -->
<div class="row">
    <!-- Event form -->
    <form class="ui form expand" method="POST" action="{% url 'team:events' team.id %}">
        <h4 class="ui dividing header">
            Create an Event
        </h4>
        <div class="field">
            <label>Name</label>
            <input type="text" name="title" placeholder="Title" maxlength="255" value="{{ form.data.title }}" required>
        </div>
        <div class="two fields">
            <div class="field">
                <label>Start Date</label>
                <input type="date" name="start" value="{{ form.data.start }}" required>
            </div>
            <div class="field">
                <label>End Date</label>
                <input type="date" name="end" value="{{ form.data.end }}" required>
            </div>
        </div>
        <div class="field">
            <label>Description</label>
            <textarea name="description" placeholder="Description" rows="2" maxlength="255" required>{{ form.data.description }}</textarea>
        </div>
        {% csrf_token %}
        <button class="ui green button" type="submit">
            Create
        </button>
    </form>
    {% if events %}
    <!-- Event list -->
    <h4 class="ui dividing header expand">
        Event List
    </h4>
    {% for event in events %}
    <div class="ui small message expand">
        <div class="message header">
            {{ event.title }}: {{ event.start|date:"M d, Y" }} - {{ event.end|date:"M d, Y" }}
        </div>
        <p>{{ event.description }} - <em>{{ event.owner.get_full_name }}</em></p>
    </div>
    {% endfor %}
    {% endif %}
</div>
{% endblock %}

templates/backend/team/files.html
{% extends 'backend/layouts/base.html' %}
{% load static %}

{% block title %}
{{ team.name }}: Files
{% endblock %}

{% block body %}
<!-- Page title -->
<div class="ui secondary pointing fluid menu">
    <h2 class="ui header">
        {{ team.name }}
        <div class="sub header">
            Files
        </div>
    </h2>
</div>

<!-- Notifications -->
{% include 'backend/partials/notifications.html' %}

<!-- Body -->
<div class="row">
    <!-- Hidden upload form -->
    <form id="hidden" method="POST" action="{% url 'team:files' team.id %}">
        <input type="hidden" name="file_id">
        {% csrf_token %}
    </form>
    <button class="ui google plus button expand" onclick="loadPicker()">
        <i class="google icon"></i>
        Share a file from Google Drive
    </button>
    <!-- List of files -->
    {% if files %}
    <h4 class="ui dividing header expand">
        Shared Files
    </h4>
    {% for file in files %}
    <div class="ui small message download">
        <table>
            <tr>
                <td>
                    <div class="message header">
                        {{ file.name }}
                    </div>
                    Uploaded by {{ file.owner.get_full_name }}, {{ file.created|timesince }} ago
                </td>
                <td>
                    <a href="?file_id={{ file.id }}">
                        <i class="download icon"></i>
                    </a>
                </td>
            </tr>
        </table>
    </div>
    {% endfor %}
    {% endif %}
</div>
{% endblock %}

{% block scripts %}
<script type="text/javascript" src="{% static 'js/backend.picker.js' %}"></script>
<script type="text/javascript" src="https://apis.google.com/js/api.js"></script>
<script type="text/javascript">initPicker('{{ google.API_KEY }}', '{{ google.CLIENT_ID }}', '{{ google.APP_ID }}');</script>
{% endblock %}

templates/backend/team/home.html
{% extends 'backend/layouts/base.html' %}
{% load static %}
{% load utils %}

{% block title %}
{{ team.name }}: About
{% endblock %}

{% block styles %}
<!-- Markdown styles -->
<link rel="stylesheet" href="{% static 'css/backend.md.css' %}"/>
{% endblock %}

{% block body %}
<!-- Page title -->
<div class="ui secondary pointing fluid menu">
    <h2 class="ui header">
        {{ team.name }}
        <div class="sub header">
            Home
        </div>
    </h2>
</div>

<!-- Notifications -->
{% include 'backend/partials/notifications.html' %}

<!-- Description -->
<div>
    {{ team.description|markdown }}
</div>
{% endblock %}

templates/backend/team/manage_edit.html
{% extends 'backend/layouts/base.html' %}

{% block title %}
{{ team.name }}: Edit
{% endblock %}

{% block body %}
<!-- Page title -->
<div class="ui secondary pointing fluid menu">
    <h2 class="ui header">
        {{ team.name }}
        <div class="sub header">
            Manage
        </div>
    </h2>
    <div class="right menu">
        <a class="ui active item">
            Edit
        </a>
        <a class="ui item" href="{% url 'team:manage:users' team.id %}">
            Users
        </a>
    </div>
</div>

<!-- Notifications -->
{% include 'backend/partials/notifications.html' %}

<!-- Body -->
<div class="row">
    {% include 'backend/partials/team_form.html' %}
</div>
{% endblock %}

templates/backend/team/manage_users.html
{% extends 'backend/layouts/base.html' %}
{% load static %}

{% block title %}
{{ team.name }}: Edit Users
{% endblock %}

{% block body %}
<!-- Page title -->
<div class="ui secondary pointing fluid menu">
    <h2 class="ui header">
        {{ team.name }}
        <div class="sub header">
            Manage
        </div>
    </h2>
    <div class="right menu">
        <a class="ui item" href="{% url 'team:manage:edit' team.id %}">
            Edit
        </a>
        <a class="ui active item">
            Users
        </a>
    </div>
</div>

<!-- Notifications -->
{% include 'backend/partials/notifications.html' %}

<!-- Body -->
<div class="row">
    <!-- Invitation form -->
    <form class="ui form" method="POST" action="{% url 'team:manage:users' team.id %}">
        <h4 class="ui dividing header">
            Invite Users
        </h4>
        <table class="simple form">
            <tr>
                <td>
                    <div class="field">
                        <input type="email" name="email" placeholder="Email address" value="{{ form.data.email }}" required>
                    </div>
                </td>
                <td>
                    {% csrf_token %}
                    <button class="ui green button" type="submit">
                        Invite
                    </button>
                </td>
            </tr>
        </table>
    </form>
    <!-- User table -->
    {% if team.members > 1 %}
    <table class="ui very basic striped celled table user view">
        <thead>
            <tr>
                <th>User</th>
                <th>Member Since</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            {% for user in users %}
            {% if user.id != request.user.id %}
            <tr>
                <td>{{ user.user.get_full_name }}</td>
                <td>{{ user.created|date:"M d, Y" }}</td>
                <td>
                    <a class="ui red button" onclick="remove('{{ user.user.id }}')">
                        Remove
                    </a>
                </td>
            </tr>
            {% endif %}
            {% endfor %}
        </tbody>
    </table>
    {% endif %}
    <!-- Hidden remove form -->
    <form id="hidden" method="POST" action="{% url 'team:manage:users' team.id %}">
        <input type="hidden" name="id">
        {% csrf_token %}
    </form>
</div>
{% endblock %}

{% block scripts %}
<!-- Hidden form controller -->
<script type="text/javascript" src="{% static 'js/backend.manage.js' %}"></script>
{% endblock %}

templates/backend/team/users.html
{% extends 'backend/layouts/base.html' %}

{% block title %}
{{ team.name }}: Users
{% endblock %}

{% block body %}
<!-- Page title -->
<div class="ui secondary pointing fluid menu">
    <h2 class="ui header">
        {{ team.name }}
        <div class="sub header">
            Users
        </div>
    </h2>
</div>

<!-- Notifications -->
{% include 'backend/partials/notifications.html' %}

<!-- Body -->
<div class="row">
    <table class="ui very basic striped celled table user view">
        <thead>
            <tr>
                <th>User</th>
                <th>Member Since</th>
            </tr>
        </thead>
        <tbody>
            {% for user in users %}
            <tr>
                <td>{{ user.user.get_full_name }}</td>
                <td>{{ user.created|date:"M d, Y" }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}