teamspace/urls.py
"""
URL Configuration

For more information on URLs, see:
https://docs.djangoproject.com/en/1.10/topics/http/urls/
"""
from django.conf.urls import include
from django.conf.urls import url
from teamspace.views import dashboard
from teamspace.views import frontend
from teamspace.views import google
from teamspace.views import organization
from teamspace.views import team

handler403 = 'teamspace.views.error'
handler404 = 'teamspace.views.error'

urlpatterns = [
    # Frontend routes
    url(
        r'^',
        include(
            [
                url(r'^$', frontend.home, name='home'),
                url(r'^about/$', frontend.about, name='about'),
                url(r'^login/$', frontend.login, name='login'),
                url(r'^logout/$', frontend.logout, name='logout'),
                url(r'^signup/$', frontend.signup, name='signup'),
            ],
            namespace='frontend',
        ),
    ),

    # Dashboard routes
    url(
        r'^d/',
        include(
            [
                # Root dashboard routes
                url(r'^$', dashboard.home, name='home'),

                # Account management routes
                url(
                    r'^u/',
                    include(
                        [
                            url(
                                r'^edit/$',
                                dashboard.user_edit,
                                name='edit',
                            ),
                            url(
                                r'^password/$',
                                dashboard.user_password,
                                name='password',
                            ),
                        ],
                        namespace='user',
                    ),
                ),

                # Organization access/creation routes
                url(
                    r'^o/',
                    include(
                        [
                            url(
                                r'^create/$',
                                dashboard.orgs_create,
                                name='create',
                            ),
                            url(
                                r'^view/$',
                                dashboard.orgs_view,
                                name='view',
                            ),
                        ],
                        namespace='organization',
                    ),
                ),
            ],
            namespace='dashboard',
        ),
    ),

    # Organization routes
    url(
        r'^o/([0-9]+)/',
        include(
            [
                # Root organization routes
                url(r'^$', organization.home, name='home'),
                url(r'^delete/$', organization.delete, name='delete'),
                url(r'^leave/$', organization.leave, name='leave'),
                url(r'^users/$', organization.users, name='users'),

                # Organization management routes
                url(
                    r'^m/',
                    include(
                        [
                            url(
                                r'^edit/$',
                                organization.manage_edit,
                                name='edit',
                            ),
                            url(
                                r'^users/$',
                                organization.manage_users,
                                name='users',
                            ),
                        ],
                        namespace='manage',
                    ),
                ),

                # Team access/creation routes
                url(
                    r'^t/',
                    include(
                        [
                            url(
                                r'^create/$',
                                organization.teams_create,
                                name='create',
                            ),
                            url(
                                r'^view/$',
                                organization.teams_view,
                                name='view',
                            ),
                        ],
                        namespace='team',
                    ),
                ),
            ],
            namespace='organization',
        ),
    ),

    # Team routes
    url(
        r'^t/([0-9]+)/',
        include(
            [
                # Root team routes
                url(r'^$', team.home, name='home'),
                url(r'^chat/$', team.chat, name='chat'),
                url(r'^delete/$', team.delete, name='delete'),
                url(r'^events/$', team.events, name='events'),
                url(r'^files/$', team.files, name='files'),
                url(r'^leave/$', team.leave, name='leave'),
                url(r'^users/$', team.users, name='users'),

                # Team management routes
                url(
                    r'^m/',
                    include(
                        [
                            url(r'^edit/$', team.manage_edit, name='edit'),
                            url(r'^users/$', team.manage_users, name='users'),
                        ],
                        namespace='manage',
                    ),
                ),
            ],
            namespace='team',
        ),
    ),

    # Provider routes
    url(
        r'^providers/',
        include(
            [url(r'^google/$', google.index, name='google')],
            namespace='providers',
        ),
    ),
]

teamspace/views/frontend.py
"""
Frontend Controller

For more information on controllers (views), see:
https://docs.djangoproject.com/en/1.10/#the-view-layer

For the full list of requests and their responses, see:
https://docs.djangoproject.com/en/1.10/ref/request-response/
"""
from django.contrib.auth import login as user_login
from django.contrib.auth import logout as user_logout
from django.http import JsonResponse
from django.shortcuts import redirect
from django.shortcuts import render
from teamspace.decorators import require_logged_out
from teamspace.forms import UserLoginForm
from teamspace.forms import UserSignupForm


@require_logged_out
def home(request):
    """
    Returns a basic view that acts as a starting point for Teamspace.
    """
    return render(request, 'frontend/home.html')


@require_logged_out
def about(request):
    """
    Returns a basic view containing information about Teamspace.
    """
    return render(request, 'frontend/about.html')


def logout(request):
    """
    Logs a user out and redirects them back home.
    """
    user_logout(request)
    return redirect('frontend:home')


def login(request):
    """
    This simple endpoint logs a user in.
    """
    if request.method == 'POST':
        # Process the post data in the form
        form = UserLoginForm(request.POST)

        if form.is_valid():
            # Check if the form is valid
            user = form.user
            user_login(request, user)
            return JsonResponse({'valid': True})
        else:
            # Respond with the errors otherwise
            return JsonResponse({'valid': False, 'errors': form.errors})

    # Redirect the user back home otherwise
    return redirect('frontend:home')


def signup(request):
    """
    This simple endpoint creates a user.
    """
    if request.method == 'POST':
        # Process the post data in the form
        form = UserSignupForm(request.POST)

        if form.is_valid():
            # Check if the form is valid
            user = form.save()
            user_login(request, user)
            return JsonResponse({'valid': True})
        else:
            # Respond with the errors otherwise
            return JsonResponse({'valid': False, 'errors': form.errors})

    # Redirect the user back home otherwise
    return redirect('frontend:home')

templates/frontend/layouts/base.html
{% load static %}
{% load utils %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
        {% endblock %}
    </title>
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.4/semantic.min.css"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/frontend.css' %}"/>
    {% block styles %}
    {% endblock %}
</head>
<body>
<!-- Log in form -->
<form class="ui small modal" id="login" method="POST" action="{% url 'frontend:login' %}">
    <div class="header">Log in to Teamspace.</div>
    <div class="content">
        <div class="ui form">
            <div class="field" id="login-email">
                <div class="ui left icon input">
                    <i class="mail icon"></i>
                    <input type="email" name="email" placeholder="Email address" required>
                </div>
            </div>
            <div class="field" id="login-password">
                <div class="ui left icon input">
                    <i class="lock icon"></i>
                    <input type="password" name="password" placeholder="Password" required>
                </div>
            </div>
        </div>
        <br/>
        <div align="center">
            Don't have an account? <a href="#" onclick="signup()">Sign up</a>.
        </div>
        <div class="ui error message" id="login-errors">
            <div class="header">There were some problems.</div>
            <ul class="list">
            </ul>
        </div>
    </div>
    <div class="actions">
        {% csrf_token %}
        <button class="ui cancel button" type="reset" onclick="resetLoginForm()">
            Cancel
        </button>
        <button class="ui green submit button" type="submit">
            Log in
        </button>
    </div>
</form>
<!-- Sign up form -->
<form class="ui small modal" id="signup" method="POST" action="{% url 'frontend:signup' %}">
    <div class="header">Sign up for Teamspace.</div>
    <div class="content">
        <div class="ui form">
            <div class="two fields">
                <div class="field" id="signup-first-name">
                    <div class="ui left icon input">
                        <i class="user icon"></i>
                        <input type="text" name="first_name" placeholder="First name" maxlength="30" required>
                    </div>
                </div>
                <div class="field" id="signup-last-name">
                    <div class="ui left icon input">
                        <i class="user icon"></i>
                        <input type="text" name="last_name" placeholder="Last name" maxlength="30" required>
                    </div>
                </div>
            </div>
            <div class="two fields">
                <div class="field" id="signup-username">
                    <div class="ui left icon input">
                        <i class="browser icon"></i>
                        <input type="text" name="username" placeholder="Username" maxlength="20" required>
                    </div>
                </div>
                <div class="field" id="signup-email">
                    <div class="ui left icon input">
                        <i class="mail icon"></i>
                        <input type="email" name="email" placeholder="Email address" required>
                    </div>
                </div>
            </div>
            <div class="field" id="signup-password-one">
                <div class="ui left icon input">
                    <i class="lock icon"></i>
                    <input type="password" name="password_one" placeholder="Password" required>
                </div>
            </div>
            <div class="field" id="signup-password-two">
                <div class="ui left icon input">
                    <i class="lock icon"></i>
                    <input type="password" name="password_two" placeholder="Confirm password" required>
                </div>
            </div>
        </div>
        <br/>
        <div align="center">
            Already have an account? <a href="#" onclick="login()">Log in</a>.
        </div>
        <div class="ui error message" id="signup-errors">
            <div class="header">There were some problems.</div>
            <ul class="list"></ul>
        </div>
    </div>
    <div class="actions">
        {% csrf_token %}
        <button class="ui cancel button" type="reset" onclick="resetSignupForm()">
            Cancel
        </button>
        <button class="ui green submit button" type="submit">
            Sign up
        </button>
    </div>
</form>
<!-- Floating menu -->
<div class="ui large top fixed hidden menu">
    <div class="ui container">
        <a class="{% if request|viewname:'frontend:home' %}active {% endif %}item"
           href="{% url 'frontend:home' %}">
            Home
        </a>
        <a class="{% if request|viewname:'frontend:about' %}active {% endif %}item"
           href="{% url 'frontend:about' %}">
            About
        </a>
        <div class="right menu">
            <div class="item">
                <a class="ui button" onclick="login()">
                    Log in
                </a>
            </div>
            <div class="item">
                <a class="ui primary button" onclick="signup()">
                    Sign up
                </a>
            </div>
        </div>
    </div>
</div>
<!-- Side menu -->
<div class="ui vertical inverted sidebar menu">
    <a class="{% if request|viewname:'frontend:home' %}active {% endif %}item"
       href="{% url 'frontend:home' %}">
        Home
    </a>
    <a class="{% if request|viewname:'frontend:about' %}active {% endif %}item"
       href="{% url 'frontend:about' %}">
        About
    </a>
</div>
<div class="pusher">
    <!-- Top menu -->
    <div class="ui inverted vertical masthead center aligned segment breakpoint">
        <div class="ui container">
            <div class="ui large secondary inverted pointing menu">
                <a class="toc item">
                    <i class="sidebar icon"></i>
                </a>
                <a class="{% if request|viewname:'frontend:home' %}active {% endif %}item"
                   href="{% url 'frontend:home' %}">
                    Home
                </a>
                <a class="{% if request|viewname:'frontend:about' %}active {% endif %}item"
                   href="{% url 'frontend:about' %}">
                    About
                </a>
                <div class="right item">
                    <a class="ui inverted button" onclick="login()">
                        Log in
                    </a>
                    <a class="ui inverted button" onclick="signup()">
                        Sign up
                    </a>
                </div>
            </div>
        </div>
        {% block masthead %}
        {% endblock %}
    </div>
    {% block body %}
    {% endblock %}
    {% if request.resolver_match.view_name != 'frontend:home' %}
    <!-- Footer -->
    <div class="ui inverted vertical footer segment">
        <div class="ui container">
            <div class="ui stackable inverted divided equal height stackable grid">
                <div class="three wide column">
                    <h4 class="ui inverted header">About</h4>
                    <div class="ui inverted link list">
                        <a href="#" class="item">Sitemap</a>
                        <a href="#" class="item">Contact Us</a>
                    </div>
                </div>
                <div class="three wide column">
                    <h4 class="ui inverted header">Services</h4>
                    <div class="ui inverted link list">
                        <a href="#" class="item">Pricing</a>
                        <a href="#" class="item">Conditions</a>
                    </div>
                </div>
                <div class="seven wide column">
                    <h4 class="ui inverted header">Footer Header</h4>
                    <p>Some text here.</p>
                </div>
            </div>
        </div>
    </div>
    {% endif %}
</div>
<script type="text/javascript" src="https://code.jquery.com/jquery-3.1.0.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.4/semantic.min.js"></script>
<script type="text/javascript" src="{% static 'js/frontend.js' %}"></script>
<script type="text/javascript" src="{% static 'js/frontend.forms.js' %}"></script>
{% block scripts %}
{% endblock %}
</body>
</html>