teamspace/urls.py
"""
URL Configuration

For more information on URLs, see:
https://docs.djangoproject.com/en/1.10/topics/http/urls/
"""
from django.conf.urls import include
from django.conf.urls import url
from teamspace.views import dashboard
from teamspace.views import frontend
from teamspace.views import google
from teamspace.views import organization
from teamspace.views import team

handler403 = 'teamspace.views.error'
handler404 = 'teamspace.views.error'

urlpatterns = [
    # Frontend routes
    url(
        r'^',
        include(
            [
                url(r'^$', frontend.home, name='home'),
                url(r'^about/$', frontend.about, name='about'),
                url(r'^login/$', frontend.login, name='login'),
                url(r'^logout/$', frontend.logout, name='logout'),
                url(r'^signup/$', frontend.signup, name='signup'),
            ],
            namespace='frontend',
        ),
    ),

    # Dashboard routes
    url(
        r'^d/',
        include(
            [
                # Root dashboard routes
                url(r'^$', dashboard.home, name='home'),

                # Account management routes
                url(
                    r'^u/',
                    include(
                        [
                            url(
                                r'^edit/$',
                                dashboard.user_edit,
                                name='edit',
                            ),
                            url(
                                r'^password/$',
                                dashboard.user_password,
                                name='password',
                            ),
                        ],
                        namespace='user',
                    ),
                ),

                # Organization access/creation routes
                url(
                    r'^o/',
                    include(
                        [
                            url(
                                r'^create/$',
                                dashboard.orgs_create,
                                name='create',
                            ),
                            url(
                                r'^view/$',
                                dashboard.orgs_view,
                                name='view',
                            ),
                        ],
                        namespace='organization',
                    ),
                ),
            ],
            namespace='dashboard',
        ),
    ),

    # Organization routes
    url(
        r'^o/([0-9]+)/',
        include(
            [
                # Root organization routes
                url(r'^$', organization.home, name='home'),
                url(r'^delete/$', organization.delete, name='delete'),
                url(r'^leave/$', organization.leave, name='leave'),
                url(r'^users/$', organization.users, name='users'),

                # Organization management routes
                url(
                    r'^m/',
                    include(
                        [
                            url(
                                r'^edit/$',
                                organization.manage_edit,
                                name='edit',
                            ),
                            url(
                                r'^users/$',
                                organization.manage_users,
                                name='users',
                            ),
                        ],
                        namespace='manage',
                    ),
                ),

                # Team access/creation routes
                url(
                    r'^t/',
                    include(
                        [
                            url(
                                r'^create/$',
                                organization.teams_create,
                                name='create',
                            ),
                            url(
                                r'^view/$',
                                organization.teams_view,
                                name='view',
                            ),
                        ],
                        namespace='team',
                    ),
                ),
            ],
            namespace='organization',
        ),
    ),

    # Team routes
    url(
        r'^t/([0-9]+)/',
        include(
            [
                # Root team routes
                url(r'^$', team.home, name='home'),
                url(r'^chat/$', team.chat, name='chat'),
                url(r'^delete/$', team.delete, name='delete'),
                url(r'^events/$', team.events, name='events'),
                url(r'^files/$', team.files, name='files'),
                url(r'^leave/$', team.leave, name='leave'),
                url(r'^users/$', team.users, name='users'),

                # Team management routes
                url(
                    r'^m/',
                    include(
                        [
                            url(r'^edit/$', team.manage_edit, name='edit'),
                            url(r'^users/$', team.manage_users, name='users'),
                        ],
                        namespace='manage',
                    ),
                ),
            ],
            namespace='team',
        ),
    ),

    # Provider routes
    url(
        r'^providers/',
        include(
            [url(r'^google/$', google.index, name='google')],
            namespace='providers',
        ),
    ),
]

teamspace/views/dashboard.py
"""
Dashboard Controller

For more information on controllers (views), see:
https://docs.djangoproject.com/en/1.10/#the-view-layer

For the full list of requests and their responses, see:
https://docs.djangoproject.com/en/1.10/ref/request-response/
"""
from django.contrib import messages
from django.shortcuts import redirect
from django.shortcuts import render
from teamspace.decorators import require_logged_in
from teamspace.forms import OrganizationCreateForm
from teamspace.models import Organization
from teamspace.utils import format_errors


@require_logged_in
def home(request):
    """
    Returns a view that acts as a starting point for the user.
    """
    return render(request, 'backend/dashboard/home.html')


@require_logged_in
def user_edit(request):
    """
    Returns a view with a form for the user to edit their account.
    """
    return render(request, 'backend/dashboard/user_edit.html')


@require_logged_in
def user_password(request):
    """
    Returns a view with a form for the user to change their password.
    """
    return render(request, 'backend/dashboard/user_password.html')


@require_logged_in
def orgs_view(request):
    """
    Returns a view containing a list of organizations the user is a member of.
    """
    organizations = (
        Organization.objects
            .defer(*Organization.DEFER)
            .filter(organizationmembership__user=request.user)
    )

    for organization in organizations:
        # Fetch a list of active teams for each organization
        organization.load_active_teams(request.user)

    if not organizations:
        # Flash a message if the list of teams is empty
        messages.info(
            request,
            "You're not a member of any organization yet. Go create one!",
        )

    # Render the template with the data set
    return render(
        request,
        'backend/dashboard/organizations_view.html',
        {'organizations': organizations},
    )


@require_logged_in
def orgs_create(request):
    """
    Returns a view where users can create an organization.
    """
    if request.method == 'POST':
        # Process the post data in the form
        form = OrganizationCreateForm(request.POST, owner=request.user)

        if form.is_valid():
            # Check if the form is valid
            organization = form.save()
            messages.success(request, 'Organization successfully created.')

            # Redirect to the newly created team
            return redirect('organization:home', organization.id)
        else:
            messages.error(request, format_errors(form.errors))

            # Return with the errors otherwise
            return render(
                request,
                'backend/dashboard/organizations_create.html',
                {'form': form},
            )

    # Render the creation template
    return render(request, 'backend/dashboard/organizations_create.html')

teamspace/views/organization.py
"""
Organization Controller

For more information on controllers (views), see:
https://docs.djangoproject.com/en/1.10/#the-view-layer

For the full list of requests and their responses, see:
https://docs.djangoproject.com/en/1.10/ref/request-response/
"""
from django.contrib import messages
from django.http import Http404
from django.shortcuts import redirect
from django.shortcuts import render
from teamspace.decorators import require_logged_in
from teamspace.decorators import require_org_member
from teamspace.decorators import require_org_owner
from teamspace.forms import AddMember
from teamspace.forms import OrganizationEditForm
from teamspace.forms import TeamCreateForm
from teamspace.models import Organization
from teamspace.models import OrganizationMembership
from teamspace.models import Team
from teamspace.utils import format_errors


@require_logged_in
@require_org_member
def leave(request, id):
    """
    Deletes the membership record if the user is a member.
    """
    try:
        organization = Organization.objects.get(pk=id)
    except Organization.DoesNotExist:
        raise Http404
    try:
        membership = (
            OrganizationMembership.objects
                .get(user=request.user, organization=organization)
        )
    except OrganizationMembership.DoesNotExist:
        raise Http404

    if membership:
        # Delete the membership record
        membership.delete()
        organization.members -= 1
        organization.save()
        messages.info(request, 'You have left the organization.')

    # Redirect the user back to the organization view
    return redirect('dashboard:organization:view')


@require_logged_in
@require_org_owner
def delete(request, id):
    """
    Deletes the organization if the user is the owner.
    """
    try:
        organization = Organization.objects.get(pk=id)
    except Organization.DoesNotExist:
        raise Http404

    if organization.owner == request.user:
        # Make sure the user is the owner
        organization.delete()
        messages.info(request, 'The organization has been deleted.')

    # Redirect the user back to the organization view
    return redirect('dashboard:organization:view')


@require_logged_in
@require_org_member
def home(request, id):
    """
    Returns a view with the organization and a parsed markdown description.
    """
    try:
        organization = Organization.objects.get(pk=id)
    except Organization.DoesNotExist:
        raise Http404

    # Render the template with the data set
    return render(
        request,
        'backend/organization/home.html',
        {'organization': organization},
    )


@require_logged_in
@require_org_member
def users(request, id):
    """
    Returns a view containing a list of members in the organization.
    """
    try:
        organization = (
            Organization.objects
                .defer(*Organization.DEFER)
                .get(pk=id)
        )
    except Organization.DoesNotExist:
        raise Http404

    # Get a list of organization members
    users = (
        OrganizationMembership.objects
            .select_related('user')
            .filter(organization=organization)
    )

    # Render the template with the data set
    return render(
        request,
        'backend/organization/users.html',
        {'users': users, 'organization': organization},
    )


@require_logged_in
@require_org_member
def teams_view(request, id):
    """
    Returns a view containing a list of teams in the organization.
    """
    try:
        organization = (
            Organization.objects
                .defer(*Organization.DEFER)
                .get(pk=id)
        )
    except Organization.DoesNotExist:
        raise Http404

    # TODO: If the user is the organization owner, show all the teams.
    # TODO: If they are not the owner, only show teams where they are a member.

    # Fetch the corresponding list of teams
    teams = organization.team_set.defer(*Team.DEFER).all()

    if not teams:
        # Flash a message if the list of teams is empty
        messages.info(
            request,
            'Your organization does not have any teams. Go create one!',
        )

    # Render the template with the data set
    return render(
        request,
        'backend/organization/teams_view.html',
        {'teams': teams, 'organization': organization},
    )


@require_logged_in
@require_org_member
def teams_create(request, id):
    """
    Returns a view where users can create a team within the organization.
    """
    try:
        organization = (
            Organization.objects
                .defer(*Organization.DEFER)
                .get(pk=id)
        )
    except Organization.DoesNotExist:
        raise Http404

    if request.method == 'POST':
        # Process the post data in the form
        form = TeamCreateForm(
            request.POST,
            parent=organization,
            owner=request.user,
        )

        if form.is_valid():
            # Check if the form is valid
            team = form.save()
            messages.success(request, 'Team successfully created.')

            # Redirect to the newly created team
            return redirect('team:home', team.id)
        else:
            messages.error(request, format_errors(form.errors))

            # Return with the errors otherwise
            return render(
                request,
                'backend/organization/teams_create.html',
                {'form': form, 'organization': organization},
            )

    # Render the template with the data set
    return render(
        request,
        'backend/organization/teams_create.html',
        {'organization': organization},
    )


@require_logged_in
@require_org_owner
def manage_edit(request, id):
    """
    Returns a view where an owner can edit their organization.
    """
    try:
        organization = Organization.objects.get(pk=id)
    except Organization.DoesNotExist:
        raise Http404

    if request.method == 'POST':
        # Update the form with the post data
        form = OrganizationEditForm(request.POST, instance=organization)

        if form.is_valid():
            # Check if the form is valid
            form.save()
            messages.success(request, 'Settings successfully saved.')
        else:
            messages.error(request, format_errors(form.errors))
    else:
        # Initialize the default form
        form = OrganizationEditForm(instance=organization)

    # Render the template with the data set
    return render(
        request,
        'backend/organization/manage_edit.html',
        {'form': form, 'organization': organization},
    )


@require_logged_in
@require_org_owner
def manage_users(request, id):
    """
    Returns a view with a list of users and a form to add users.
    """
    try:
        organization = (
            Organization.objects
                .defer(*Organization.DEFER)
                .get(pk=id)
        )
    except Organization.DoesNotExist:
        raise Http404
    form = None

    if request.method == 'POST':
        if 'email' in request.POST:
            # Handle invitations by creating a membership record
            form = AddMember(request.POST, group=organization)

            if form.is_valid():
                # Check if the form is valid
                form.add_member()
                organization.members += 1
                organization.save()
                messages.success(request, 'User successfully added.')
            else:
                messages.error(request, format_errors(form.errors))

        if 'id' in request.POST:
            # Handle removals by deleting the membership record
            # `id` is not user controlled, so assume it's safe
            remove_user_id = int(request.POST['id'])

            try:
                # Find and delete the membership record
                (
                    OrganizationMembership.objects
                        .get(user_id=remove_user_id, organization=organization)
                        .delete()
                )
            except OrganizationMembership.DoesNotExist:
                raise Http404
            organization.members -= 1
            organization.save()

    # Get a list of organization members
    users = (
        OrganizationMembership.objects
            .select_related('user')
            .filter(organization=organization)
    )

    if organization.members == 1:
        # Check if the member count only includes the owner
        messages.info(
            request,
            'Your organization does not have any members. Invite some!',
        )

    # Render the template with the data set
    return render(
        request,
        'backend/organization/manage_users.html',
        {'users': users, 'form': form, 'organization': organization},
    )

templates/backend/dashboard/home.html
{% extends 'backend/layouts/base.html' %}
{% load static %}

{% block title %}
Dashboard: Home
{% endblock %}

{% block styles %}
<!-- Add some spacing between the buttons -->
<link rel="stylesheet" href="{% static 'css/backend.grid.css' %}"/>
{% endblock %}

{% block body %}
<!-- Page title -->
<div class="ui secondary pointing fluid menu">
    <h2 class="ui header">
        Dashboard
        <div class="sub header">
            Home
        </div>
    </h2>
</div>

<!-- Notifications -->
{% include 'backend/partials/notifications.html' %}

<!-- Body -->
<div class="row">
    <table class="expand">
        <tr>
            <td class="dashboard">
                <a class="fluid ui green back nav button" href="{% url 'dashboard:organization:view' %}">
                    <h2>Organizations</h2>
                    <h4>Select an organization to get started.</h4>
                </a>
            </td>
            <td class="dashboard">
                <a class="fluid ui blue back nav button" href="{% url 'dashboard:user:edit' %}">
                    <h2>Account</h2>
                    <h4>View, edit, or delete your account.</h4>
                </a>
            </td>
        </tr>
    </table>
</div>
{% endblock %}

templates/backend/dashboard/organizations_create.html
{% extends 'backend/layouts/base.html' %}

{% block title %}
Dashboard: Create Organization
{% endblock %}

{% block body %}
<!-- Page title -->
<div class="ui secondary pointing fluid menu">
    <h2 class="ui header">
        Organizations
        <div class="sub header">
            Create
        </div>
    </h2>
    <div class="right menu">
        <a class="ui item" href="{% url 'dashboard:organization:view' %}">
            Select
        </a>
        <a class="ui active item">
            Create
        </a>
    </div>
</div>

<!-- Notifications -->
{% include 'backend/partials/notifications.html' %}

<!-- Body -->
<div class="row">
    {% include 'backend/partials/organization_form.html' %}
</div>
{% endblock %}

{% block scripts %}
<!-- Organization form -->
<script type="text/javascript">
    var country = '{{ form.data.country }}';
    var state = '{{ form.data.state }}';
    $('[name=country]').dropdown('set selected', country);
    $('[name=state]').dropdown('set selected', state);
</script>
{% endblock %}

templates/backend/dashboard/organizations_view.html
{% extends 'backend/layouts/base.html' %}
{% load static %}

{% block title %}
Dashboard: View Organizations
{% endblock %}

{% block body %}
<!-- Delete-leave modal -->
<div class="ui small modal" id="verify">
    <div class="header" id="verify-title"></div>
    <div class="content">
        <div align="center" id="verify-description"></div>
    </div>
    <div class="actions">
        <a class="ui cancel button" type="reset">
            Cancel
        </a>
        <a class="ui red submit button" id="verify-link" type="submit"></a>
    </div>
</div>

<!-- Page title -->
<div class="ui secondary pointing fluid menu">
    <h2 class="ui header">
        Organizations
        <div class="sub header">
            Select
        </div>
    </h2>
    <div class="right menu">
        <a class="ui active item">
            Select
        </a>
        <a class="ui item" href="{% url 'dashboard:organization:create' %}">
            Create
        </a>
    </div>
</div>

<!-- Notifications -->
{% include 'backend/partials/notifications.html' %}

<!-- Body -->
<div class="row">
    {% if organizations %}
    <table class="ui very basic striped celled table org view">
        <thead>
            <tr>
                <th>Organization</th>
                <th>Active Teams</th>
                <th>Members</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            {% for organization in organizations %}
            <tr>
                <td>{{ organization.name }}</td>
                <td>
                    {% if organization.active_teams %}
                        {% for active_team in organization.active_teams %}
                            {% if forloop.last %}
                                {{ active_team.name }}.
                            {% else %}
                                {{ active_team.name }},
                            {% endif %}
                        {% endfor %}
                    {% else %}
                        (No active teams)
                    {% endif %}
                </td>
                <td>{{ organization.members }}</td>
                <td>
                    {% if organization.owner == request.user %}
                     <div class="ui blue buttons">
                         <a class="ui button" href="{% url 'organization:team:view' organization.id %}">
                             Select
                         </a>
                         <div class="ui floating dropdown icon button">
                             <i class="dropdown icon"></i>
                             <div class="menu">
                                 <a class="item" href="{% url 'organization:manage:edit' organization.id %}">
                                     <i class="edit icon"></i> Manage
                                 </a>
                                 <a class="item" onclick="verify('{% url 'organization:delete' organization.id %}', 'delete', 'organization')">
                                     <i class="delete icon"></i> Delete
                                 </a>
                             </div>
                         </div>
                     </div>
                     {% else %}
                     <div class="ui green buttons">
                        <a class="ui button" href="{% url 'organization:team:view' organization.id %}">
                            Select
                        </a>
                        <div class="ui floating dropdown icon button">
                            <i class="dropdown icon"></i>
                            <div class="menu">
                                <a class="item" onclick="verify('{% url 'organization:leave' organization.id %}', 'leave', 'organization')">
                                    <i class="sign out icon"></i> Leave
                                </a>
                            </div>
                        </div>
                     </div>
                     {% endif %}
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% endif %}
</div>
{% endblock %}

{% block scripts %}
<!-- Delete-leave modal -->
<script type="text/javascript" src="{% static 'js/backend.manage.js' %}"></script>
{% endblock %}

templates/backend/dashboard/user_edit.html
{% extends 'backend/layouts/base.html' %}

{% block title %}
Dashboard: Edit Account
{% endblock %}

{% block body %}
<!-- Page title -->
<div class="ui secondary pointing fluid menu">
    <h2 class="ui header">
        Account
        <div class="sub header">
            Settings
        </div>
    </h2>
    <div class="right menu">
        <a class="ui active item">
            Edit Account
        </a>
        <a class="ui item" href="{% url 'dashboard:user:password' %}">
            Change Password
        </a>
    </div>
</div>

<!-- Notifications -->
{% include 'backend/partials/notifications.html' %}

<!-- Body -->
<div class="row">
    <!-- Edit account information -->
    <form class="ui form expand" method="POST">
        <h4 class="ui dividing header">
            Account Information
        </h4>
        <div class="two fields">
            <div class="field">
                <label>First name</label>
                <input type="text" name="first_name" placeholder="First name" maxlength="30" required>
            </div>
            <div class="field">
                <label>Last name</label>
                <input type="text" name="last_name" placeholder="Last name" maxlength="30" required>
            </div>
        </div>
        <div class="two fields">
            <div class="field">
                <label>Username</label>
                <input type="text" name="username" placeholder="Username" maxlength="20" required>
            </div>
            <div class="field">
                <label>Email address</label>
                <input type="email" name="email" placeholder="Email address" required>
            </div>
        </div>
        <div class="field">
            <label>Confirm password</label>
            <div class="ui left icon input">
                <i class="lock icon"></i>
                <input type="password" name="password_two" placeholder="Confirm password" required>
            </div>
        </div>
        <br/>
        {% csrf_token %}
        <button class="ui green button" type="submit">
            Save
        </button>
    </form>
</div>
{% endblock %}

templates/backend/dashboard/user_password.html
{% extends 'backend/layouts/base.html' %}

{% block title %}
Dashboard: Change Password
{% endblock %}

{% block body %}
<!-- Page title -->
<div class="ui secondary pointing fluid menu">
    <h2 class="ui header">
        Account
        <div class="sub header">
            Settings
        </div>
    </h2>
    <div class="right menu">
        <a class="ui item" href="{% url 'dashboard:user:edit' %}">
            Edit Account
        </a>
        <a class="ui active item">
            Change Password
        </a>
    </div>
</div>

<!-- Notifications -->
{% include 'backend/partials/notifications.html' %}

<!-- Body -->
<div class="row">
    <!-- Change password -->
    <form class="ui form expand" method="POST">
        <h4 class="ui dividing header">
            Change Password
        </h4>
        <div class="field">
            <label>Old password</label>
            <div class="ui left icon input">
                <i class="lock icon"></i>
                <input type="password" name="password_old" placeholder="Old password" required>
            </div>
        </div>
        <div class="field">
            <label>New password</label>
            <div class="ui left icon input">
                <i class="lock icon"></i>
                <input type="password" name="password_one" placeholder="New password" required>
            </div>
        </div>
        <div class="field">
            <label>Confirm new password</label>
            <div class="ui left icon input">
                <i class="lock icon"></i>
                <input type="password" name="password_two" placeholder="Confirm new password" required>
            </div>
        </div>
        <br/>
        {% csrf_token %}
        <button class="ui green button" type="submit">
            Save
        </button>
    </form>
</div>
{% endblock %}