teamspace/urls.py
"""
URL Configuration

For more information on URLs, see:
https://docs.djangoproject.com/en/1.10/topics/http/urls/
"""
from django.conf.urls import include
from django.conf.urls import url
from teamspace.views import dashboard
from teamspace.views import frontend
from teamspace.views import google
from teamspace.views import organization
from teamspace.views import team

handler403 = 'teamspace.views.error'
handler404 = 'teamspace.views.error'

urlpatterns = [
    # Frontend routes
    url(
        r'^',
        include(
            [
                url(r'^$', frontend.home, name='home'),
                url(r'^about/$', frontend.about, name='about'),
                url(r'^login/$', frontend.login, name='login'),
                url(r'^logout/$', frontend.logout, name='logout'),
                url(r'^signup/$', frontend.signup, name='signup'),
            ],
            namespace='frontend',
        ),
    ),

    # Dashboard routes
    url(
        r'^d/',
        include(
            [
                # Root dashboard routes
                url(r'^$', dashboard.home, name='home'),

                # Account management routes
                url(
                    r'^u/',
                    include(
                        [
                            url(
                                r'^edit/$',
                                dashboard.user_edit,
                                name='edit',
                            ),
                            url(
                                r'^password/$',
                                dashboard.user_password,
                                name='password',
                            ),
                        ],
                        namespace='user',
                    ),
                ),

                # Organization access/creation routes
                url(
                    r'^o/',
                    include(
                        [
                            url(
                                r'^create/$',
                                dashboard.orgs_create,
                                name='create',
                            ),
                            url(
                                r'^view/$',
                                dashboard.orgs_view,
                                name='view',
                            ),
                        ],
                        namespace='organization',
                    ),
                ),
            ],
            namespace='dashboard',
        ),
    ),

    # Organization routes
    url(
        r'^o/([0-9]+)/',
        include(
            [
                # Root organization routes
                url(r'^$', organization.home, name='home'),
                url(r'^delete/$', organization.delete, name='delete'),
                url(r'^leave/$', organization.leave, name='leave'),
                url(r'^users/$', organization.users, name='users'),

                # Organization management routes
                url(
                    r'^m/',
                    include(
                        [
                            url(
                                r'^edit/$',
                                organization.manage_edit,
                                name='edit',
                            ),
                            url(
                                r'^users/$',
                                organization.manage_users,
                                name='users',
                            ),
                        ],
                        namespace='manage',
                    ),
                ),

                # Team access/creation routes
                url(
                    r'^t/',
                    include(
                        [
                            url(
                                r'^create/$',
                                organization.teams_create,
                                name='create',
                            ),
                            url(
                                r'^view/$',
                                organization.teams_view,
                                name='view',
                            ),
                        ],
                        namespace='team',
                    ),
                ),
            ],
            namespace='organization',
        ),
    ),

    # Team routes
    url(
        r'^t/([0-9]+)/',
        include(
            [
                # Root team routes
                url(r'^$', team.home, name='home'),
                url(r'^chat/$', team.chat, name='chat'),
                url(r'^delete/$', team.delete, name='delete'),
                url(r'^events/$', team.events, name='events'),
                url(r'^files/$', team.files, name='files'),
                url(r'^leave/$', team.leave, name='leave'),
                url(r'^users/$', team.users, name='users'),

                # Team management routes
                url(
                    r'^m/',
                    include(
                        [
                            url(r'^edit/$', team.manage_edit, name='edit'),
                            url(r'^users/$', team.manage_users, name='users'),
                        ],
                        namespace='manage',
                    ),
                ),
            ],
            namespace='team',
        ),
    ),

    # Provider routes
    url(
        r'^providers/',
        include(
            [url(r'^google/$', google.index, name='google')],
            namespace='providers',
        ),
    ),
]

teamspace/models/team.py
from django.db import models


class Team(models.Model):

    # Database fields
    owner = models.ForeignKey(
        'teamspace.User',
        on_delete=models.CASCADE,
    )
    parent = models.ForeignKey(
        'teamspace.Organization',
        on_delete=models.CASCADE,
    )
    name = models.CharField(max_length=100)
    description = models.TextField(max_length=50000)
    members = models.IntegerField(default=1)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    # Constants
    DEFER = ['description']

teamspace/forms/organization.py
"""
Organization Forms

For more information on Forms, see:
https://docs.djangoproject.com/en/1.10/topics/forms/

For more information on ModelForms, see:
https://docs.djangoproject.com/en/1.10/topics/forms/modelforms/
"""
from django import forms
from teamspace.models import Organization
from teamspace.models import OrganizationMembership


class BaseOrganizationForm(forms.ModelForm):

    class Meta:
        model = Organization
        fields = ['name', 'description', 'address', 'country', 'state']
        errors = {
            'name': {
                'required': 'Please enter the name of your organization.',
                'unique': 'This organization name is taken.',
            },
            'description': {
                'required': 'Please enter an organization description.',
            },
        }


class OrganizationCreateForm(BaseOrganizationForm):

    def __init__(self, *args, **kwargs):
        self.owner = kwargs.pop('owner')
        super().__init__(*args, **kwargs)

    def save(self, commit=True):
        organization = super().save(commit=False)
        organization.owner = self.owner
        if commit:
            organization.save()
            OrganizationMembership.objects.create(
                organization=organization,
                user=organization.owner,
            )
        return organization


class OrganizationEditForm(BaseOrganizationForm):
    pass

teamspace/forms/team.py
"""
Team Forms

For more information on Forms, see:
https://docs.djangoproject.com/en/1.10/topics/forms/

For more information on ModelForms, see:
https://docs.djangoproject.com/en/1.10/topics/forms/modelforms/
"""
from django import forms
from teamspace.models import Team
from teamspace.models import TeamMembership


class BaseTeamForm(forms.ModelForm):

    class Meta:
        model = Team
        fields = ['name', 'description']
        error_messages = {
            'name': {
                'required': 'Please enter your team name.',
                'unique': 'This team name is taken.',
            },
            'description': {
                'required': 'Please enter a team description.',
            },
        }


class TeamCreateForm(BaseTeamForm):

    def __init__(self, *args, **kwargs):
        self.owner = kwargs.pop('owner')
        self.parent = kwargs.pop('parent')
        super().__init__(*args, **kwargs)

    def save(self, commit=True):
        team = super().save(commit=False)
        team.owner = self.owner
        team.parent = self.parent
        if commit:
            team.save()
            TeamMembership.objects.create(team=team, user=team.owner)
        return team


class TeamEditForm(BaseTeamForm):
    pass

teamspace/views/organization.py
"""
Organization Controller

For more information on controllers (views), see:
https://docs.djangoproject.com/en/1.10/#the-view-layer

For the full list of requests and their responses, see:
https://docs.djangoproject.com/en/1.10/ref/request-response/
"""
from django.contrib import messages
from django.http import Http404
from django.shortcuts import redirect
from django.shortcuts import render
from teamspace.decorators import require_logged_in
from teamspace.decorators import require_org_member
from teamspace.decorators import require_org_owner
from teamspace.forms import AddMember
from teamspace.forms import OrganizationEditForm
from teamspace.forms import TeamCreateForm
from teamspace.models import Organization
from teamspace.models import OrganizationMembership
from teamspace.models import Team
from teamspace.utils import format_errors


@require_logged_in
@require_org_member
def leave(request, id):
    """
    Deletes the membership record if the user is a member.
    """
    try:
        organization = Organization.objects.get(pk=id)
    except Organization.DoesNotExist:
        raise Http404
    try:
        membership = (
            OrganizationMembership.objects
                .get(user=request.user, organization=organization)
        )
    except OrganizationMembership.DoesNotExist:
        raise Http404

    if membership:
        # Delete the membership record
        membership.delete()
        organization.members -= 1
        organization.save()
        messages.info(request, 'You have left the organization.')

    # Redirect the user back to the organization view
    return redirect('dashboard:organization:view')


@require_logged_in
@require_org_owner
def delete(request, id):
    """
    Deletes the organization if the user is the owner.
    """
    try:
        organization = Organization.objects.get(pk=id)
    except Organization.DoesNotExist:
        raise Http404

    if organization.owner == request.user:
        # Make sure the user is the owner
        organization.delete()
        messages.info(request, 'The organization has been deleted.')

    # Redirect the user back to the organization view
    return redirect('dashboard:organization:view')


@require_logged_in
@require_org_member
def home(request, id):
    """
    Returns a view with the organization and a parsed markdown description.
    """
    try:
        organization = Organization.objects.get(pk=id)
    except Organization.DoesNotExist:
        raise Http404

    # Render the template with the data set
    return render(
        request,
        'backend/organization/home.html',
        {'organization': organization},
    )


@require_logged_in
@require_org_member
def users(request, id):
    """
    Returns a view containing a list of members in the organization.
    """
    try:
        organization = (
            Organization.objects
                .defer(*Organization.DEFER)
                .get(pk=id)
        )
    except Organization.DoesNotExist:
        raise Http404

    # Get a list of organization members
    users = (
        OrganizationMembership.objects
            .select_related('user')
            .filter(organization=organization)
    )

    # Render the template with the data set
    return render(
        request,
        'backend/organization/users.html',
        {'users': users, 'organization': organization},
    )


@require_logged_in
@require_org_member
def teams_view(request, id):
    """
    Returns a view containing a list of teams in the organization.
    """
    try:
        organization = (
            Organization.objects
                .defer(*Organization.DEFER)
                .get(pk=id)
        )
    except Organization.DoesNotExist:
        raise Http404

    # TODO: If the user is the organization owner, show all the teams.
    # TODO: If they are not the owner, only show teams where they are a member.

    # Fetch the corresponding list of teams
    teams = organization.team_set.defer(*Team.DEFER).all()

    if not teams:
        # Flash a message if the list of teams is empty
        messages.info(
            request,
            'Your organization does not have any teams. Go create one!',
        )

    # Render the template with the data set
    return render(
        request,
        'backend/organization/teams_view.html',
        {'teams': teams, 'organization': organization},
    )


@require_logged_in
@require_org_member
def teams_create(request, id):
    """
    Returns a view where users can create a team within the organization.
    """
    try:
        organization = (
            Organization.objects
                .defer(*Organization.DEFER)
                .get(pk=id)
        )
    except Organization.DoesNotExist:
        raise Http404

    if request.method == 'POST':
        # Process the post data in the form
        form = TeamCreateForm(
            request.POST,
            parent=organization,
            owner=request.user,
        )

        if form.is_valid():
            # Check if the form is valid
            team = form.save()
            messages.success(request, 'Team successfully created.')

            # Redirect to the newly created team
            return redirect('team:home', team.id)
        else:
            messages.error(request, format_errors(form.errors))

            # Return with the errors otherwise
            return render(
                request,
                'backend/organization/teams_create.html',
                {'form': form, 'organization': organization},
            )

    # Render the template with the data set
    return render(
        request,
        'backend/organization/teams_create.html',
        {'organization': organization},
    )


@require_logged_in
@require_org_owner
def manage_edit(request, id):
    """
    Returns a view where an owner can edit their organization.
    """
    try:
        organization = Organization.objects.get(pk=id)
    except Organization.DoesNotExist:
        raise Http404

    if request.method == 'POST':
        # Update the form with the post data
        form = OrganizationEditForm(request.POST, instance=organization)

        if form.is_valid():
            # Check if the form is valid
            form.save()
            messages.success(request, 'Settings successfully saved.')
        else:
            messages.error(request, format_errors(form.errors))
    else:
        # Initialize the default form
        form = OrganizationEditForm(instance=organization)

    # Render the template with the data set
    return render(
        request,
        'backend/organization/manage_edit.html',
        {'form': form, 'organization': organization},
    )


@require_logged_in
@require_org_owner
def manage_users(request, id):
    """
    Returns a view with a list of users and a form to add users.
    """
    try:
        organization = (
            Organization.objects
                .defer(*Organization.DEFER)
                .get(pk=id)
        )
    except Organization.DoesNotExist:
        raise Http404
    form = None

    if request.method == 'POST':
        if 'email' in request.POST:
            # Handle invitations by creating a membership record
            form = AddMember(request.POST, group=organization)

            if form.is_valid():
                # Check if the form is valid
                form.add_member()
                organization.members += 1
                organization.save()
                messages.success(request, 'User successfully added.')
            else:
                messages.error(request, format_errors(form.errors))

        if 'id' in request.POST:
            # Handle removals by deleting the membership record
            # `id` is not user controlled, so assume it's safe
            remove_user_id = int(request.POST['id'])

            try:
                # Find and delete the membership record
                (
                    OrganizationMembership.objects
                        .get(user_id=remove_user_id, organization=organization)
                        .delete()
                )
            except OrganizationMembership.DoesNotExist:
                raise Http404
            organization.members -= 1
            organization.save()

    # Get a list of organization members
    users = (
        OrganizationMembership.objects
            .select_related('user')
            .filter(organization=organization)
    )

    if organization.members == 1:
        # Check if the member count only includes the owner
        messages.info(
            request,
            'Your organization does not have any members. Invite some!',
        )

    # Render the template with the data set
    return render(
        request,
        'backend/organization/manage_users.html',
        {'users': users, 'form': form, 'organization': organization},
    )

templates/backend/partials/menu.html
{% load static %}
{% load utils %}

<!-- Dashboard link -->
<a class="item first" href="{% url 'dashboard:home' %}">
    <h4 align="center">Dashboard</h4>
</a>

{% if organization %}
<!-- Organization menu -->
<div class="item">
    <b>{{ organization.name }}</b>
</div>
<a class="{% if request|viewname:'organization:home' %}active {% endif %}item"
   href="{% url 'organization:home' organization.id %}">
    <small>Home</small>
    <i class="home icon"></i>
</a>
<a class="{% if request|viewname:'organization:users' %}active {% endif %}item"
   href="{% url 'organization:users' organization.id %}">
    <small>Users</small>
    <i class="users icon"></i>
</a>
<a class="{% if request|namespace:'organization:team' %}active {% endif %}item"
   href="{% url 'organization:team:view' organization.id %}">
    <small>Teams</small>
    <i class="th list icon"></i>
</a>
{% if organization.owner == request.user %}
<a class="{% if request|namespace:'organization:manage' %}active {% endif %}item"
   href="{% url 'organization:manage:edit' organization.id %}">
    <small>Manage</small>
    <i class="cogs icon"></i>
</a>
{% endif %}
{% endif %}

{% if team %}
<!-- Team menu -->
<div class="item">
    <b>{{ team.name }}</b>
</div>
<a class="{% if request|viewname:'team:home' %}active {% endif %}item"
   href="{% url 'team:home' team.id %}">
    <small>Home</small>
    <i class="home icon"></i>
</a>
<a class="{% if request|viewname:'team:users' %}active {% endif %}item"
   href="{% url 'team:users' team.id %}">
    <small>Users</small>
    <i class="users icon"></i>
</a>
<a class="{% if request|viewname:'team:events' %}active {% endif %}item"
   href="{% url 'team:events' team.id %}">
    <small>Events</small>
    <i class="calendar icon"></i>
</a>
<a class="{% if request|viewname:'team:chat' %}active {% endif %}item"
   href="{% url 'team:chat' team.id %}">
    <small>Chat</small>
    <i class="comments icon"></i>
</a>
<a class="{% if request|viewname:'team:files' %}active {% endif %}item"
   href="{% url 'team:files' team.id %}">
    <small>Files</small>
    <i class="folder open icon"></i>
</a>
{% if team.owner == request.user %}
<a class="{% if request|namespace:'team:manage' %}active {% endif %}item"
   href="{% url 'team:manage:edit' team.id %}">
    <small>Manage</small>
    <i class="cogs icon"></i>
</a>
{% endif %}
{% endif %}

<!-- Log out -->
<a class="item" href="{% url 'frontend:logout' %}">
    <h4 class="ui grey header">{{ request.user.get_full_name }}</h4>
    <p>Log out</p>
</a>

templates/backend/partials/notifications.html
{% if messages %}
{% for message in messages %}
<div class="ui icon{% if message.tags %} {{ message.tags }}{% endif %} message">
    <i class="close icon"></i>
    <div class="content">
        <div class="header">
            {% if message.level == DEFAULT_MESSAGE_LEVELS.INFO %}
                Heads up!
            {% elif message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
                Success!
            {% elif message.level == DEFAULT_MESSAGE_LEVELS.WARNING %}
                Warning!
            {% elif message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                Oh snap!
            {% endif %}
        </div>
        <p>{{ message|safe }}</p>
    </div>
</div>
{% endfor %}
{% endif %}

templates/backend/partials/team_form.html
{% load utils %}

<!-- Team from -->
<form class="ui form expand" method="POST" action="{% if request|viewname:'organization:team:create' %}{% url 'organization:team:create' organization.id %}{% elif request|viewname:'team:manage:edit' %}{% url 'team:manage:edit' team.id %}{% endif %}">
    <h4 class="ui dividing header">
        Team Information
    </h4>
    <div class="field">
        <label>Name</label>
        <input type="text" name="name" placeholder="Name" maxlength="100" value="{% if form %}{{ form.data.name|default:form.instance.name }}{% endif %}" required>
    </div>
    <div class="field">
        <label>Description</label>
        <textarea name="description" placeholder="Description" maxlength="50000" required>{% if form %}{{ form.data.description|default:form.instance.description }}{% endif %}</textarea>
        We support <a href="https://guides.github.com/features/mastering-markdown/">Markdown</a>.
    </div>
    <br/>
    {% csrf_token %}
    <button class="ui green button" type="submit">
        {% if request|viewname:'organization:team:create' %}
            Create
        {% elif request|viewname:'team:manage:edit' %}
            Save
        {% endif %}
    </button>
</form>